[package]
name = "logsnarf-rs"
version = "0.1.0"
authors = ["Paul Sadauskas <psadauskas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
time = "^0.1"
warp = "0.2"
# syslog_rfc5424 = { path = "../rust-syslog-rfc5424", version = "0.7.0" }
